/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFacilitatorRouteImport } from './routes/_authenticated/facilitator'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCourseCompletedRouteImport } from './routes/_authenticated/course-completed'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedQuizModuleIdRouteImport } from './routes/_authenticated/quiz.$moduleId'
import { Route as AuthenticatedLessonsModuleIdRouteImport } from './routes/_authenticated/lessons.$moduleId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacilitatorRoute =
  AuthenticatedFacilitatorRouteImport.update({
    id: '/facilitator',
    path: '/facilitator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourseCompletedRoute =
  AuthenticatedCourseCompletedRouteImport.update({
    id: '/course-completed',
    path: '/course-completed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizModuleIdRoute =
  AuthenticatedQuizModuleIdRouteImport.update({
    id: '/quiz/$moduleId',
    path: '/quiz/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsModuleIdRoute =
  AuthenticatedLessonsModuleIdRouteImport.update({
    id: '/lessons/$moduleId',
    path: '/lessons/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/course-completed': typeof AuthenticatedCourseCompletedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facilitator': typeof AuthenticatedFacilitatorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/lessons/$moduleId': typeof AuthenticatedLessonsModuleIdRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/course-completed': typeof AuthenticatedCourseCompletedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facilitator': typeof AuthenticatedFacilitatorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/lessons/$moduleId': typeof AuthenticatedLessonsModuleIdRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/course-completed': typeof AuthenticatedCourseCompletedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/facilitator': typeof AuthenticatedFacilitatorRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/lessons/$moduleId': typeof AuthenticatedLessonsModuleIdRoute
  '/_authenticated/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/course'
    | '/sitemap.xml'
    | '/admin'
    | '/course-completed'
    | '/dashboard'
    | '/facilitator'
    | '/profile'
    | '/lessons/$moduleId'
    | '/quiz/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/course'
    | '/sitemap.xml'
    | '/admin'
    | '/course-completed'
    | '/dashboard'
    | '/facilitator'
    | '/profile'
    | '/lessons/$moduleId'
    | '/quiz/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/course'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/course-completed'
    | '/_authenticated/dashboard'
    | '/_authenticated/facilitator'
    | '/_authenticated/profile'
    | '/_authenticated/lessons/$moduleId'
    | '/_authenticated/quiz/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CourseRoute: typeof CourseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facilitator': {
      id: '/_authenticated/facilitator'
      path: '/facilitator'
      fullPath: '/facilitator'
      preLoaderRoute: typeof AuthenticatedFacilitatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course-completed': {
      id: '/_authenticated/course-completed'
      path: '/course-completed'
      fullPath: '/course-completed'
      preLoaderRoute: typeof AuthenticatedCourseCompletedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$moduleId': {
      id: '/_authenticated/quiz/$moduleId'
      path: '/quiz/$moduleId'
      fullPath: '/quiz/$moduleId'
      preLoaderRoute: typeof AuthenticatedQuizModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/$moduleId': {
      id: '/_authenticated/lessons/$moduleId'
      path: '/lessons/$moduleId'
      fullPath: '/lessons/$moduleId'
      preLoaderRoute: typeof AuthenticatedLessonsModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCourseCompletedRoute: typeof AuthenticatedCourseCompletedRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFacilitatorRoute: typeof AuthenticatedFacilitatorRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedLessonsModuleIdRoute: typeof AuthenticatedLessonsModuleIdRoute
  AuthenticatedQuizModuleIdRoute: typeof AuthenticatedQuizModuleIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCourseCompletedRoute: AuthenticatedCourseCompletedRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFacilitatorRoute: AuthenticatedFacilitatorRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedLessonsModuleIdRoute: AuthenticatedLessonsModuleIdRoute,
  AuthenticatedQuizModuleIdRoute: AuthenticatedQuizModuleIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CourseRoute: CourseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
