/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LearningHubRouteImport } from './routes/learning-hub'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFinalExamRouteImport } from './routes/_authenticated/final-exam'
import { Route as AuthenticatedFacilitatorRouteImport } from './routes/_authenticated/facilitator'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCourseCompletedRouteImport } from './routes/_authenticated/course-completed'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedQuizModuleIdRouteImport } from './routes/_authenticated/quiz.$moduleId'
import { Route as AuthenticatedLessonsModuleIdRouteImport } from './routes/_authenticated/lessons.$moduleId'

const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubRoute = LearningHubRouteImport.update({
  id: '/learning-hub',
  path: '/learning-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinalExamRoute = AuthenticatedFinalExamRouteImport.update({
  id: '/final-exam',
  path: '/final-exam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacilitatorRoute =
  AuthenticatedFacilitatorRouteImport.update({
    id: '/facilitator',
    path: '/facilitator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourseCompletedRoute =
  AuthenticatedCourseCompletedRouteImport.update({
    id: '/course-completed',
    path: '/course-completed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizModuleIdRoute =
  AuthenticatedQuizModuleIdRouteImport.update({
    id: '/quiz/$moduleId',
    path: '/quiz/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsModuleIdRoute =
  AuthenticatedLessonsModuleIdRouteImport.update({
    id: '/lessons/$moduleId',
    path: '/lessons/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/courses': typeof CoursesRoute
  '/curriculum': typeof CurriculumRoute
  '/faqs': typeof FaqsRoute
  '/learning-hub': typeof LearningHubRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/course-completed': typeof AuthenticatedCourseCompletedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facilitator': typeof AuthenticatedFacilitatorRoute
  '/final-exam': typeof AuthenticatedFinalExamRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/lessons/$moduleId': typeof AuthenticatedLessonsModuleIdRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/courses': typeof CoursesRoute
  '/curriculum': typeof CurriculumRoute
  '/faqs': typeof FaqsRoute
  '/learning-hub': typeof LearningHubRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/course-completed': typeof AuthenticatedCourseCompletedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facilitator': typeof AuthenticatedFacilitatorRoute
  '/final-exam': typeof AuthenticatedFinalExamRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/lessons/$moduleId': typeof AuthenticatedLessonsModuleIdRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/courses': typeof CoursesRoute
  '/curriculum': typeof CurriculumRoute
  '/faqs': typeof FaqsRoute
  '/learning-hub': typeof LearningHubRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/course-completed': typeof AuthenticatedCourseCompletedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/facilitator': typeof AuthenticatedFacilitatorRoute
  '/_authenticated/final-exam': typeof AuthenticatedFinalExamRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/lessons/$moduleId': typeof AuthenticatedLessonsModuleIdRoute
  '/_authenticated/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/course'
    | '/courses'
    | '/curriculum'
    | '/faqs'
    | '/learning-hub'
    | '/resources'
    | '/sitemap.xml'
    | '/survey'
    | '/admin'
    | '/course-completed'
    | '/dashboard'
    | '/facilitator'
    | '/final-exam'
    | '/profile'
    | '/lessons/$moduleId'
    | '/quiz/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/course'
    | '/courses'
    | '/curriculum'
    | '/faqs'
    | '/learning-hub'
    | '/resources'
    | '/sitemap.xml'
    | '/survey'
    | '/admin'
    | '/course-completed'
    | '/dashboard'
    | '/facilitator'
    | '/final-exam'
    | '/profile'
    | '/lessons/$moduleId'
    | '/quiz/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/course'
    | '/courses'
    | '/curriculum'
    | '/faqs'
    | '/learning-hub'
    | '/resources'
    | '/sitemap.xml'
    | '/survey'
    | '/_authenticated/admin'
    | '/_authenticated/course-completed'
    | '/_authenticated/dashboard'
    | '/_authenticated/facilitator'
    | '/_authenticated/final-exam'
    | '/_authenticated/profile'
    | '/_authenticated/lessons/$moduleId'
    | '/_authenticated/quiz/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CourseRoute: typeof CourseRoute
  CoursesRoute: typeof CoursesRoute
  CurriculumRoute: typeof CurriculumRoute
  FaqsRoute: typeof FaqsRoute
  LearningHubRoute: typeof LearningHubRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurveyRoute: typeof SurveyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-hub': {
      id: '/learning-hub'
      path: '/learning-hub'
      fullPath: '/learning-hub'
      preLoaderRoute: typeof LearningHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/final-exam': {
      id: '/_authenticated/final-exam'
      path: '/final-exam'
      fullPath: '/final-exam'
      preLoaderRoute: typeof AuthenticatedFinalExamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facilitator': {
      id: '/_authenticated/facilitator'
      path: '/facilitator'
      fullPath: '/facilitator'
      preLoaderRoute: typeof AuthenticatedFacilitatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course-completed': {
      id: '/_authenticated/course-completed'
      path: '/course-completed'
      fullPath: '/course-completed'
      preLoaderRoute: typeof AuthenticatedCourseCompletedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$moduleId': {
      id: '/_authenticated/quiz/$moduleId'
      path: '/quiz/$moduleId'
      fullPath: '/quiz/$moduleId'
      preLoaderRoute: typeof AuthenticatedQuizModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/$moduleId': {
      id: '/_authenticated/lessons/$moduleId'
      path: '/lessons/$moduleId'
      fullPath: '/lessons/$moduleId'
      preLoaderRoute: typeof AuthenticatedLessonsModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCourseCompletedRoute: typeof AuthenticatedCourseCompletedRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFacilitatorRoute: typeof AuthenticatedFacilitatorRoute
  AuthenticatedFinalExamRoute: typeof AuthenticatedFinalExamRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedLessonsModuleIdRoute: typeof AuthenticatedLessonsModuleIdRoute
  AuthenticatedQuizModuleIdRoute: typeof AuthenticatedQuizModuleIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCourseCompletedRoute: AuthenticatedCourseCompletedRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFacilitatorRoute: AuthenticatedFacilitatorRoute,
  AuthenticatedFinalExamRoute: AuthenticatedFinalExamRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedLessonsModuleIdRoute: AuthenticatedLessonsModuleIdRoute,
  AuthenticatedQuizModuleIdRoute: AuthenticatedQuizModuleIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CourseRoute: CourseRoute,
  CoursesRoute: CoursesRoute,
  CurriculumRoute: CurriculumRoute,
  FaqsRoute: FaqsRoute,
  LearningHubRoute: LearningHubRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurveyRoute: SurveyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
